//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnstile.Amce.v1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.acme.co.uk/wsdl/HelloService.wsdl", ConfigurationName="Turnstile.Amce.v1.Hello_PortType")]
    public interface Hello_PortType
    {
        
        // CODEGEN: Generating message contract since the operation sayHello is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Turnstile.Amce.v1.sayHelloResponse sayHello(Turnstile.Amce.v1.sayHelloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class SecurityHeaderType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public Turnstile.Amce.v1.SecurityHeaderType Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string firstName;
        
        public sayHelloRequest()
        {
        }
        
        public sayHelloRequest(Turnstile.Amce.v1.SecurityHeaderType Security, string firstName)
        {
            this.Security = Security;
            this.firstName = firstName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string greeting;
        
        public sayHelloResponse()
        {
        }
        
        public sayHelloResponse(string greeting)
        {
            this.greeting = greeting;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Hello_PortTypeChannel : Turnstile.Amce.v1.Hello_PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Hello_PortTypeClient : System.ServiceModel.ClientBase<Turnstile.Amce.v1.Hello_PortType>, Turnstile.Amce.v1.Hello_PortType
    {
        
        public Hello_PortTypeClient()
        {
        }
        
        public Hello_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Hello_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Hello_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Hello_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Turnstile.Amce.v1.sayHelloResponse Turnstile.Amce.v1.Hello_PortType.sayHello(Turnstile.Amce.v1.sayHelloRequest request)
        {
            return base.Channel.sayHello(request);
        }
        
        public string sayHello(Turnstile.Amce.v1.SecurityHeaderType Security, string firstName)
        {
            Turnstile.Amce.v1.sayHelloRequest inValue = new Turnstile.Amce.v1.sayHelloRequest();
            inValue.Security = Security;
            inValue.firstName = firstName;
            Turnstile.Amce.v1.sayHelloResponse retVal = ((Turnstile.Amce.v1.Hello_PortType)(this)).sayHello(inValue);
            return retVal.greeting;
        }
    }
}
